# Generated by Django 4.0 on 2021-12-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question_difficulty_question_objective'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_name',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('course__course_name',)},
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
